#+---------------------------------------------+
#|                                             |
#|   Helluva                                   |
#|                                             |
#+---------------------------------------------+
on death:
    set {_x} to random integer between -1000 and 1000
    set {_z} to random integer between -1000 and 1000
    set {_y} to random integer between 32 and 100 
    
    set {_loc} to location at {_x}, {_y}, {_z} in world "world_nether"
    
    teleport victim to {_loc}
    send "&cYou have died and been sent to a random spot in the Nether!" to victim
#/////////////////////////////////////////////////////////////////////////////////////////////
#ticket out of hell
#////////////////////////////////////////////////////////////////////////////////////////////
#gui needed here
#idea: pay gold to get out of hell (pay inside a gui)
#///////////////////////////////////////////////////////////////////////////////////////////